settings:
  # Branding
  APP_DISPLAY_NAME: ketal
  PRODUCTION_APP_NAME: ketal
  APP_GROUP_IDENTIFIER: group.io.ketal
  BASE_BUNDLE_IDENTIFIER: io.ketal.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: DQM48A6L3K

  # Custom Configuration (Injected via apply_ketal_config.sh)
  KETAL_DOMAIN_BASE: ketals.online
  KETAL_DOMAIN_MATRIX: matrix.ketals.online
  KETAL_DOMAIN_AUTH: auth.ketals.online
  
  KETAL_OIDC_REDIRECT_URI: ketal://oidc
  KETAL_OIDC_CLIENT_NAME: ketal
  
  # Push
  KETAL_PUSH_FALLBACK_URL: https://sygnal.ketals.online
